# Generated by Django 3.1.8 on 2025-12-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='require_tool_confirmation',
            field=models.BooleanField(default=False, help_text="When enabled, you'll be asked to confirm before the assistant executes any tools", verbose_name='Require confirmation before executing tools'),
        ),
    ]
