# Generated by Django 3.1.8 on 2025-12-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_tool_confirmations',
            field=models.BooleanField(default=True, help_text="When enabled, you'll see confirmation messages when the assistant executes tools", verbose_name='Show tool execution confirmations'),
        ),
    ]
