# Generated by Django 3.1.8 on 2025-12-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_require_tool_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='require_tool_confirmation',
        ),
        migrations.AddField(
            model_name='user',
            name='show_tool_confirmations',
            field=models.BooleanField(default=True, help_text="When enabled, you'll see confirmation messages when the assistant executes tools", verbose_name='Show tool execution confirmations'),
        ),
    ]
