# Generated by Django 4.2.20 on 2025-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intentions_page", "0012_auto_20210816_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="intention",
            name="sticky",
            field=models.BooleanField(default=False),
        ),
    ]
