# Generated by Django 4.2.20 on 2025-12-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intentions_page", "0013_intention_sticky"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intention",
            options={"ordering": ["-froggy", "created_datetime"]},
        ),
        migrations.AddField(
            model_name="intention",
            name="froggy",
            field=models.BooleanField(default=False),
        ),
    ]
