# Generated by Django 4.2.20 on 2025-12-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intentions_page", "0014_alter_intention_options_intention_froggy"),
    ]

    operations = [
        migrations.AddField(
            model_name="intention",
            name="anxiety_inducing",
            field=models.BooleanField(default=False),
        ),
    ]
