# Generated by Django 4.2.20 on 2025-12-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intentions_page", "0015_intention_anxiety_inducing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intention",
            options={"ordering": ["created_datetime"]},
        ),
    ]
