# Generated by Django 3.1.8 on 2025-12-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0017_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='intention',
            options={'ordering': ['order', 'created_datetime']},
        ),
    ]
