# Generated by Django 3.1.8 on 2025-12-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0018_add_order_field_to_intention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
