# Generated by Django 3.1.8 on 2025-12-18 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intentions_page', '0019_add_index_to_order_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField()),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['user', '-timestamp'], name='intentions__user_id_87e305_idx'),
        ),
        migrations.AddIndex(
            model_name='agentaction',
            index=models.Index(fields=['tool_name'], name='intentions__tool_na_176bc9_idx'),
        ),
    ]
