# Generated by Django 3.1.8 on 2025-12-18 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intentions_page', '0019_add_index_to_order_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringIntention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('days_of_week', models.JSONField(blank=True, null=True)),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('default_sticky', models.BooleanField(default=False)),
                ('default_froggy', models.BooleanField(default=False)),
                ('default_anxiety_inducing', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_datetime'],
            },
        ),
        migrations.AddField(
            model_name='intention',
            name='recurring_intention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_intentions', to='intentions_page.recurringintention'),
        ),
        migrations.AddIndex(
            model_name='recurringintention',
            index=models.Index(fields=['creator', 'is_active'], name='intentions__creator_28939c_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringintention',
            index=models.Index(fields=['is_active', 'frequency'], name='intentions__is_acti_eda7a2_idx'),
        ),
    ]
