# Generated by Django 3.1.8 on 2025-12-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0020_auto_20251218_1953'),
        ('intentions_page', '0020_auto_20251218_1719'),
    ]

    operations = [
    ]
